### ISSUE TITLE
Plot output not full

### ISSUE THREAD

**Issue by ysabantsev** [annacrombie/plot#24]
`$ seq 1 200 | plot -c C -x 5:0:0:3:blue -y 10:3:3 -d 50:200 -b 0:250`
Seems to give only first 128 values.

![Screenshot from 2021-09-27 07-24-34](https://user-images.githubusercontent.com/79027388/134845229-17141863-5d04-49a3-beae-a738762bfa0b.png)

**Comment by ysabantsev** [comment]
![Screenshot from 2021-09-27 07-45-12](https://user-images.githubusercontent.com/79027388/134846736-1f92c7fb-3a17-4eec-805e-62e3cfe2349f.png)
working good with changed FILE_INPUT_BUF
![Screenshot from 2021-09-27 07-46-28](https://user-images.githubusercontent.com/79027388/134846830-594619ed-ebdb-4123-ac1b-f882140c50d6.png)

**Comment by ysabantsev** [comment]
Hello. Yes, working good now. Thank you

**Comment by annacrombie** [comment]
Awesome, I've just bumped the version
